### ISSUE TITLE
Who is Rafael?

### ISSUE THREAD

**Issue by naodell** [NWUHEP/ntupleProducer#1]
Who is Rafael and why does he leave a comment saying he made a change next to his changes?  In a way, this is a nice idea, but if we all did this the code would be a ridiculous mess.  I think we can rely on the versioning system to let us know who made what changes and when they do it.

Also, he's mixing tabs and spaces which is mildly annoying.

**Comment by pollackscience** [comment]
Yeah, he's a kid of Northeastern that's doing H->Zg->nunug.  He does not have submit rights.  We can get rid of his flags; he added some extra MET shit and some MET significance.  Any changes he makes are 'reviewed' by zeynep or myself and then added to the actual code, but i don't think he's adding anything else for the time being.
