### ISSUE TITLE
Make updates to run in CMSSW_5_3_12

### ISSUE THREAD

**Issue by andreypz** [NWUHEP/ntupleProducer#10]
New MET recipes are for CMSSW_5_3_12_patch2:
https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideMETRecipe53X
It would get rid of one of PAT packages (it is always good)

**Comment by pollackscience** [comment]
monophoton analysis is diverging from regular/dalitz HZG.  this may be put off indefinitely

**Comment by pollackscience** [comment]
Works in 5_3_13 now, this issue is closed
