### ISSUE TITLE
Memory leaks in EGamma packages

### ISSUE THREAD

**Issue by andreypz** [NWUHEP/ntupleProducer#11]
Memory leaks from EGamma code affects the ntuple production on a large scale (Crab jobs crush).
The issue is posted to hypernews:
https://hypernews.cern.ch/HyperNews/CMS/get/egamma/1371.html
Yet,
Nobody is going to resolve this, probably. So we need to dig ourselves, with valgrind.

**Comment by pollackscience** [comment]
Majority of memleaks occur from TMVA.

**Comment by pollackscience** [comment]
I fixed as many leaks as I could, everything else looks intractable.  For the mean-time, we must submit many jobs
