### ISSUE TITLE
Create a New Object class: TCEGamma

### ISSUE THREAD

**Issue by andreypz** [NWUHEP/ntupleProducer#14]
A lot of the variables are common among Electron and Photon. We should combine them into a class. 
TCElctron and TCPhoton will be inherited from TCEgamma, which would be inherited from TCPhysObject as usual.

**Comment by naodell** [comment]
I would say make a TCEGamma class that inherits from TCPhysObject and then have TCElectron and TCPhoton inherit from that.  It's nice to at some level treat electrons and photons separately.

**Comment by andreypz** [comment]
Sure, that's what I meant.

**Comment by naodell** [comment]
Indeed it was.  I read it a bit too hastily.  By all means, enhance.

**Comment by andreypz** [comment]
This is now implemented in dev-andrey branch and the latest tag   v9.0.3-TCEgamma
All supercluster variables now belong to TCEGamma, while TCElectron and TCPhoton are derived from it.

Many variable names have been changed to unify them.
Also, many variables in Electron are moved from IdMaps into the class itself (IdMaps are still there for validation, but later should be removed).

PFisolation variables are also added to the TCEGamma class (only default ones: cone04 for electrons and cone 03 for Photons).

Will close this ticket once merged to master branch.

**Comment by pollackscience** [comment]
I merged it, closing
