### ISSUE TITLE
New HoverE2012 for  electrons

### ISSUE THREAD

**Issue by andreypz** [NWUHEP/ntupleProducer#16]
According to this: https://twiki.cern.ch/twiki/bin/view/CMS/HoverE2012
we need to implement new HOverE for electrons. The photons are fine, it seems.

The GsfElectron and Photon DataFormats are updated in CMSSW_5 so that the new H/E variable can be acessed directly:

```
  GsfElectron::hcalOverEcalBc();
  Photon::hadTowOverEm();
```

Important: Note that if using the above methods, the corresponding methods must be used for detector based Hcal isolation (with HCAL footprint removal corresponding to the new H/E numerator). For electrons, a dedicated method is provided for each of two cone sizes:

```
  GsfElectron::dr03HcalDepth1TowerSumEtBc();
  GsfElectron::dr04HcalDepth1TowerSumEtBc();
```

**Comment by andreypz** [comment]
The hcalOverEcalBc() is now saved in electrons, in dev-andrey
Not sure that the isolation variables are the same as suggested (we use some kind of Isolator object to get those). Need to check.

**Comment by pollackscience** [comment]
this has been pushed to master, will reopen after i find that you did something wrong
