### ISSUE TITLE
EGamma crystals

### ISSUE THREAD

**Issue by andreypz** [NWUHEP/ntupleProducer#17]
Need to address the issue of saving Ecal crystals. Currently, for the Photons, there are up to 100 (!) crystals saved, each contains 10 variables.
This accounts for 3% of the ntuple size of double electron sample.

**Comment by pollackscience** [comment]
Physical size is fairly unimportant, memory usage is. Work on that instead

**Comment by pollackscience** [comment]
Actual bug: Crystals are not properly initialized, will fix

**Comment by pollackscience** [comment]
fixed, devPollack_v9X
