### ISSUE TITLE
Resolve Trigger objects issues

### ISSUE THREAD

**Issue by andreypz** [NWUHEP/ntupleProducer#18]
At some point we need to address trigger objects saved in the ntuples.

Some ideas:
- Instead of hlt-trigger name store a ULong64 bit that tells which trigger this object belongs to. (Should correspond to the savedTriggerNames array)
- This is assuming that the same object can belong to different triggers (should check)

**Comment by pollackscience** [comment]
I agree, nate really screwed this whole thing up and inconvenienced everyone

**Comment by andreypz** [comment]
Problem with adding the trigger object is to match them to the HLT trigger path. There is no such functionality. Instead you need to know the name of the last filter of the HLT path and through that match the trigger object.
Not clear how to get those filter names for each HLT path.
More info here: 
https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideHLTAnalysis
