### ISSUE TITLE
Abandon IdMap and IsoMap

### ISSUE THREAD

**Issue by andreypz** [NWUHEP/ntupleProducer#27]
Most of the variables for Electron and Photon have been included into the class definition. We need to remove IdMaps from PhysObject definition. 
We may keep a map inside TCEgamma though, but even there it shouldn't be necessary.

**Comment by pollackscience** [comment]
Looks like you removed one of the maps, which makes sense.  We should keep one as it's a useful tool for variables they may only be temporary for a particular tag, and means we don't need to update the whole particle class in the analyzer to run a different tag.
