### ISSUE TITLE
Arbitrated Muons

### ISSUE THREAD

**Issue by andreypz** [NWUHEP/ntupleProducer#31]
Two requests from Stoyan:
muCon->SetIsTrArbitrated(muon::isGoodMuon(iMuon, muon::TrackerMuonArbitrated));
muCon->SetIsArbitrated(muon::isGoodMuon(iMuon, muon::AllArbitrated));

**Comment by pollackscience** [comment]
added.  something that could have easily been added by andrey, but he took the andrey way out.
