### ISSUE TITLE
Figure out the electron isolation issue

### ISSUE THREAD

**Issue by andreypz** [NWUHEP/ntupleProducer#33]
Photons are not removed from pf-Isolation as  Nate found out.

**Comment by andreypz** [comment]
Looks like the problem is known and described on official egamma page:
https://twiki.cern.ch/twiki/bin/view/CMS/EgammaPFBasedIsolation#Recommended_electron_vetoes_Upda
They don't seem to provide a concrete code though. 
Although it looks like it is implemented in the PFIsolationEstimator class that we are using (see EgammaAnalysis/ElectronTools/src/PFIsolationEstimator.cc in your files and look for isPhotonParticleVetoed() function) but is seems to have been done by a noob (like Brain or even worse), so there might be bugs.

Other related codes:
- an example of that photon removal in a different plugin:
  http://cmslxr.fnal.gov/lxr/source/CommonTools/ParticleFlow/plugins/PFCandWithSuperClusterExtractor.cc?v=CMSSW_5_3_13#086
- another alternative (which I think we used before): https://twiki.cern.ch/twiki/bin/view/CMS/PfIsolation (however it's not clear about the issue of photon removal here)

Why aren't we using any of those two? Where is PFIsolationEstimator.cc recommended?

**Comment by pollackscience** [comment]
For the mean time, this is as fixed as it can be without EGamma coming in and doing it correctly.  We will have 3 versions (PFIsolationEstimator, CommonTools/ParticleFlow, SCFP Remover)

**Comment by pollackscience** [comment]
EGamma POG is aware of this issue, may have to do with PAT cleaning of pfobjects, no idea on when this will be fixed
