### ISSUE TITLE
Implement Dump() function

### ISSUE THREAD

**Issue by andreypz** [NWUHEP/ntupleProducer#34]
We all have various dumping functions, more advanced individuals even have a special class for dumping stuff.
We should implement this functionality in TCObjects such a that we can call it directly from any TCPhysObject: obj.Dump(). Calling it from a Muon or Electron should overload the method and  print more stuff related to that object.

We could have two levels of dumps, obj.Dump(lvl), where lvl controls the amount of info two dump.

**Comment by pollackscience** [comment]
Dumps are now implemented, but in a cooler way.  TCPhysObject and all inherited classes can use '<<' operator to dump content.

Example 1: I want all electron info
cout << myElectronObj << endl;

Example 2: I only want pt,eta,phi shit for my muon
cout << TCPhysObject(myMuonObj) <<endl;

**Comment by andreypz** [comment]
Just for the record,
It is apparently possible to call Obj.Dump() and it will print out everything. This comes from ROOT's functionality.

**Comment by naodell** [comment]
You can also use the Obj.Print() function to just get the 4 vector info.  I
think this comes from the TLorentzVector inheritance.  Imagine what other
nice functionality has yet to be discovered...

On Wed, Jul 16, 2014 at 9:18 PM, Andrey Pozdnyakov <notifications@github.com
