### ISSUE TITLE
Add the v6.4 changes back

### ISSUE THREAD

**Issue by pollackscience** [NWUHEP/ntupleProducer#4]
I got vimdiff to work with git finally (set it for git difftool, not git diff).  So andrey can go ahead and use that to fix stuff!

**Comment by pollackscience** [comment]
Added back all I'm willing to do.  There was so little that changed, andrey basically did less than nothing.  This is the last time i take any of his requests seriously.

skimLepton wasn't even being used! How hard is it to add to the .cc file?  It looks like you got through the cfg, the header, then gave up and went to play left4dead.

**Comment by andreypz** [comment]
Why did you start with v6.4? In the instructions it says specifically for developers to start from master branch. There were two more commits after 6.4
You can also re-read an email I sent you a while ago, where I describe exactly the changes you erased (in cfg file) and should add back. They are  not there yet.
And why the hell did you add the root file?

Try it again Brian.

**Comment by pollackscience** [comment]
nah, you can do it if you want, your changes are too few and too useless.
