### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by pollackscience** [NWUHEP/ntupleProducer#6]
Zeynep claims that she was running the ntuplizer at FNAL and it failed due to excessive RAM usage.  More info as I investigate.  Andrey, contribute for once in your life.

**Comment by andreypz** [comment]
It's quite obvious why there is excess of RAM - your crazy maps everywhere. You can fix that.

**Comment by pollackscience** [comment]
nah it's probably in the photon crystals or the met MVA

**Comment by pollackscience** [comment]
i did some memory leak debugging, it is now part of my devbranch.  I stress-tested the ntuplizer on data and got to about 200k events before the job was killed due to excessive runtime.  I will merge with master once I'm done doing some jetID shit
