### ISSUE TITLE
muon variables in Ntuples; gen variables

### ISSUE THREAD

**Issue by StoyanStoynev** [NWUHEP/ntupleProducer#7]
For the Dalitz we need all the muons above 3 GeV stored or (only if all muons are making ntuple too large) at least all the (tracker OR global) muons. We need the tracker chi2/ndf and also isSoft and isTight (available muon selectors). 

For GEN: I talked with Brian - we need to store the pointer (or index) of the GEN particle and the pointer of  (index of) its mother. We don't need the grandmother variable.

**Comment by pollackscience** [comment]
genParticle class updated with mother linked-list (devPollack branch).  I tried to make sure there were no duplicates, and that ntuple run-time was not too adversely affected.  Expect the genParticle class to be larger now; Mother() will now return a pointer to the mother TCGenParticle or 0 if there are no mothers left.

**Comment by andreypz** [comment]
Muon variables added.
Mother() functionality is added.
