### ISSUE TITLE
MC samples: no any cuts; separate when possible 

### ISSUE THREAD

**Issue by StoyanStoynev** [NWUHEP/ntupleProducer#8]
We need to have NO cuts in signal MC samples. It is better to have the samples
for different channels (mu, e) separated - it is easy to mix, not so easy to "un-mix".

**Comment by andreypz** [comment]
A Madgraph sample for h -> mumugamma is produced and published as
 /Higgs_To_MuMuGamma_Dalitz_MH125_Mll_0to50_MadgraphHEFT_pythia6/andrey-AODSIM_v2-39bf61f738ba3bdb8860f0848073cc88/USER
