### ISSUE TITLE
Implement MotherID and GrandMotherID

### ISSUE THREAD

**Issue by andreypz** [NWUHEP/ntupleProducer#9]
In GenParticle class: implement two more methods:
GetMotherPDGId() and GetGrandMotherPDGId().
No need a Set method, just getters. If moter/frandmother does not exist, return 0.

**Comment by pollackscience** [comment]
unnecessary.  Just do if(particle->Mother()) particle->Mother()->getId

**Comment by andreypz** [comment]
Nothing is necessary, yet some things are convenient.

**Comment by andreypz** [comment]
In fact, the problem is more complicated: there are events when many intermediate statuses of the same particles are introduced (due to FSR/ISR). 
For example, I found events with  muon->Mother()->Mother()->Mother()->Mother()->GetPDGId()=23
We need to implement a function: GetPrimaryAncestor() that would return the  last particle in that chain.

**Comment by andreypz** [comment]
Here is the function. I implement it in my analyzer, will port it to TC class in the next merge.

TCGenParticle \* zgamma::GetPrimaryAncestor(TCGenParticle *p)
{
  while (p->Mother())
    p = p->Mother();
  return p;
}

**Comment by andreypz** [comment]
Alright, the best solution is to have that function at the analysis level. 
I tried to implement it into TCGenParticle class, but it gives seg faults. 
With more effort, I'm sure that can be implements, but for now I will stick with this in the analysis code:

```
TCGenParticle * zgamma::GetPrimaryAncestor(TCGenParticle *p)
{
  TCGenParticle *a = p;
  while (a->Mother())
    a = a->Mother();
  return a;
}
```

Closing this issue.
